window.isMobile=!1;if(/Android|webOS|iPhone|iPad|iPod|BlackBerry|IEMobile|Opera Mini/i.test(navigator.userAgent)){window.isMobile=!0}
window.isiOS=!1;if(/iPhone|iPad|iPod/i.test(navigator.userAgent)){window.isiOS=!0}
window.isiOSVersion='';if(window.isiOS){var version=(navigator.appVersion).match(/OS (\d+)_(\d+)_?(\d+)?/);if(version!==null){window.isiOSVersion=[parseInt(version[1],10),parseInt(version[2],10),parseInt(version[3]||0,10)]}}
function t_throttle(fn,threshhold,scope){var last;var deferTimer;threshhold||(threshhold=250);return function(){var context=scope||this;var now=+new Date();var args=arguments;if(last&&now<last+threshhold){clearTimeout(deferTimer);deferTimer=setTimeout(function(){last=now;fn.apply(context,args)},threshhold)}else{last=now;fn.apply(context,args)}}}
window.requestAnimationFrame=(function(){return window.requestAnimationFrame||window.webkitRequestAnimationFrame||window.mozRequestAnimationFrame||window.oRequestAnimationFrame||window.msRequestAnimationFrame||function(callback){window.setTimeout(callback,1000/60)}})();function t270_scroll(hash,offset){if(!hash)return;t270_checkLoad(hash,offset);if(hash.indexOf('#!/tproduct/')!==-1||hash.indexOf('#!/tab/')!==-1){return!0}
var isHistoryChangeAllowed=window.location.hash!==hash;var wrapperBlock=document.querySelector('.t270');var dontChangeHistory=wrapperBlock?Boolean(wrapperBlock.getAttribute('data-history-disabled')):!1;t270_scrollToEl(hash,offset);if(!dontChangeHistory&&isHistoryChangeAllowed){if(history.pushState){history.pushState(null,null,hash)}else{window.location.hash=hash}
isHistoryChangeAllowed=!1}
return!0}
function t270_checkLoad(hash,offset){if(window.t270_loadChecked)return;var sliderWrappers=document.body.querySelectorAll('.t-slds__items-wrapper');if(!sliderWrappers.length)return;var lastWrapper=sliderWrappers[sliderWrappers.length-1];var sliderImgs=lastWrapper?lastWrapper.querySelectorAll('.t-slds__bgimg'):[];var lastImg=sliderImgs[sliderImgs.length-1];var imageUrl=lastImg?window.getComputedStyle(lastImg).backgroundImage:'';imageUrl=imageUrl.substring(5,imageUrl.length-2);var preloaderImg=document.createElement('img');preloaderImg.src=imageUrl?imageUrl:'';preloaderImg.addEventListener('load',function(){t270_scroll(hash,offset);window.t270_loadChecked=!0})}
function t270_scrollToEl(hash,offset){if(document.body.getAttribute('data-scroll'))return;var scrollTargetY=t270_getTarget(hash,offset);if(isNaN(scrollTargetY))return;var body=document.body;var canSmoothScroll=window.CSS&&window.CSS.supports('scroll-behavior','smooth');if(window.isMobile&&canSmoothScroll&&'scrollBehavior' in document.documentElement.style){body.setAttribute('data-scroll','true');window.scrollTo({left:0,top:scrollTargetY,behavior:'smooth'});setTimeout(function(){body.removeAttribute('data-scroll')},500)}else{var html=document.querySelector('html');var documentHeight=Math.max(body.scrollHeight,body.offsetHeight,body.clientHeight,html.offsetHeight);var scrollY=window.scrollY||document.documentElement.scrollTop;var speed=2000;var time=Math.max(.1,Math.min(Math.abs(scrollY-scrollTargetY)/speed,.8));var currentTime=0;function t270_easeInQuad(pos){return Math.pow(pos,2)}
function t270_animationScroll(){currentTime+=1/60;var newDocumentHeight=Math.max(body.scrollHeight,body.offsetHeight,body.clientHeight,html.offsetHeight);if(documentHeight<newDocumentHeight){documentHeight=newDocumentHeight;scrollTargetY=t270_getTarget(hash,offset);scrollY=window.scrollY||document.documentElement.scrollTop;time=Math.max(.1,Math.min(Math.abs(scrollY-scrollTargetY)/speed,.8))}
var difference=currentTime/time;var animation=t270_easeInQuad(difference);if(difference<1){requestAnimationFrame(t270_animationScroll);window.scrollTo(0,scrollY+((scrollTargetY-scrollY)*animation))}else{body.removeAttribute('data-scroll');body.removeAttribute('data-scrollable');window.scrollTo(0,scrollTargetY)}}
body.setAttribute('data-scroll','true');body.setAttribute('data-scrollable','true');t270_animationScroll()}}
function t270_getTarget(hash,offset){var target;try{if(hash.substring(0,1)==='#'){target=document.getElementById(hash.substring(1))}else{target=document.querySelector(hash)}}catch(event){console.log('Exception t270: '+event.message);return}
if(!target){target=document.querySelector('a[name="'+hash.substr(1)+'"], div[id="'+hash.substr(1)+'"]');if(!target)return}
target=parseInt((target.getBoundingClientRect().top+window.pageYOffset)-offset,10);target=Math.max(target,0);return target}
function t397_init(recid){var rec=document.getElementById('rec'+recid);if(!rec)return;var allRecords=document.getElementById('allrecords');var tildaMode=allRecords?allRecords.getAttribute('data-tilda-mode'):'';var tildaLazyMode=allRecords?allRecords.getAttribute('data-tilda-lazy'):'';var tabs=rec?rec.querySelectorAll('.t397__tab'):[];if(tildaMode!=='edit'&&tildaMode!=='preview'){t397_scrollToTabs(recid);var activeTab=rec.querySelector('.t397__tab_active');if(activeTab){var currentButton=activeTab.querySelector('.t397__title');if(currentButton){currentButton.setAttribute('tabindex',0);currentButton.setAttribute('aria-selected',!0)}
var currentTabIndex=activeTab.getAttribute('data-tab-number');var wrapper=rec.querySelector('.t397__wrapper');wrapper.setAttribute('data-tab-current',currentTabIndex)}}
t397_addAttributesToBlocksInsideTabs(recid,tabs);Array.prototype.forEach.call(tabs,function(tab,i){tab.setAttribute('data-tab-index',i);tab.addEventListener('click',function(event){var tabNumber=i+1;var targetTab=event.target.closest('.t397__tab');if(targetTab&&targetTab.classList.contains('t397__tab_active')&&!event.isTrusted)return;t397_switchBetweenTabs(recid,tabNumber,targetTab,tildaMode,tildaLazyMode)});tab.addEventListener('keydown',function(event){var currentIndex=Number(rec.querySelector('.t397__wrapper').getAttribute('data-tab-current'));var targetTab=event.target.closest('.t397__tab');if(targetTab&&targetTab.classList.contains('t397__tab_active')&&!event.isTrusted)return;var prevent=!1;switch(event.key){case 'Left':case 'ArrowLeft':currentIndex=currentIndex===1?tabs.length:currentIndex-1;targetTab=rec.querySelector('[data-tab-number="'+currentIndex+'"]');t397_switchBetweenTabs(recid,currentIndex,targetTab,tildaMode,tildaLazyMode);t397_showActiveTabFromKeyboard(recid,currentIndex,tabs);prevent=!0;break;case 'Right':case 'ArrowRight':currentIndex=currentIndex===tabs.length?1:currentIndex+1;targetTab=rec.querySelector('[data-tab-number="'+currentIndex+'"]');t397_switchBetweenTabs(recid,currentIndex,targetTab,tildaMode,tildaLazyMode);t397_showActiveTabFromKeyboard(recid,currentIndex,tabs);prevent=!0;break;default:break}
if(prevent){event.stopPropagation();event.preventDefault()}})});if(tabs.length){t397_alltabs_updateContent(recid);t397_updateContentBySelect(recid);var bgColor=rec?rec.style.backgroundColor:'#ffffff';var bgColorTargets=rec.querySelectorAll('.t397__select, .t397__firefoxfix');Array.prototype.forEach.call(bgColorTargets,function(target){target.style.background=bgColor})}
document.addEventListener('click',function(e){if(e.target.closest('[href*="#!/tab/'+recid+'"]')){var currentLink=e.target.closest('[href*="#!/tab/'+recid+'"]');var hash=currentLink.hash;t397_scrollToTabs(recid,hash)}})}
function t397_addAttributesToBlocksInsideTabs(recid,tabs){if(tabs.length>0){Array.prototype.forEach.call(tabs,function(tab,i){var firstBlockInsideTabId=tab.getAttribute('data-tab-rec-ids').split(',')[0];var firstBlockInsideTab=document.querySelector('#rec'+firstBlockInsideTabId);if(firstBlockInsideTab&&!firstBlockInsideTab.getAttribute('aria-labelledby')){firstBlockInsideTab.setAttribute('aria-labelledby','tab'+(i+1)+'_'+recid)}
if(firstBlockInsideTab&&!firstBlockInsideTab.getAttribute('role')){firstBlockInsideTab.setAttribute('role','tabpanel')}
if(firstBlockInsideTab&&!firstBlockInsideTab.getAttribute('tabindex')){firstBlockInsideTab.setAttribute('tabindex','0')}})}}
function t397_switchBetweenTabs(recid,tabNumber,targetTab,tildaMode,tildaLazyMode){var rec=document.getElementById('rec'+recid);if(!rec)return;var activeTab=rec.querySelector('.t397__tab_active');if(activeTab){activeTab.classList.remove('t397__tab_active');var activeButton=activeTab.querySelector('.t397__title');if(activeButton){activeButton.setAttribute('tabindex',-1);activeButton.setAttribute('aria-selected',!1)}}
targetTab.classList.add('t397__tab_active');var targetButton=targetTab.querySelector('.t397__title');if(targetButton){targetButton.setAttribute('tabindex',0);targetButton.setAttribute('aria-selected',!0)}
t397_removeUrl();if(tildaMode!=='edit'&&tildaMode!=='preview'&&tabNumber&&typeof history.replaceState!=='undefined'){try{window.history.replaceState('','',window.location.origin+window.location.pathname+'#!/tab/'+recid+'-'+tabNumber)}catch(err){}}
rec.querySelector('.t397__wrapper').setAttribute('data-tab-current',tabNumber);t397_alltabs_updateContent(recid);t397_updateSelect(recid);var hookBlocks=targetTab.getAttribute('data-tab-rec-ids').split(',');var event=document.createEvent('Event');event.initEvent('displayChanged',!0,!0);var hooksCopy=hookBlocks.slice();hooksCopy.forEach(function(recid){var currentRec=document.getElementById('rec'+recid);if(!currentRec)return;var recordType=currentRec.getAttribute('data-record-type');if(recordType==='395'||recordType==='397'){var selector='.t'+recordType+'__tab_active';var activeIDs=currentRec.querySelector(selector).getAttribute('data-tab-rec-ids');activeIDs=activeIDs.split(',');hookBlocks=hookBlocks.concat(activeIDs)}});hookBlocks.forEach(function(curRecid){var currentRec=document.getElementById('rec'+curRecid);if(!currentRec)return;var currentRecChildren=currentRec.querySelectorAll('.t-feed, .t-store, .t-store__product-snippet, .t117, .t121, .t132, .t223, .t226, .t228, .t229, .t230, .t268, .t279, .t341, .t346, .t347, .t349, .t351, .t353, .t384, .t385, .t386, .t396, .t400, .t404, .t409, .t410, .t412, .t418, .t422, .t425, .t428, .t433, .t448, .t456, .t477, .t478, .t480, .t486, .t498, .t504, .t506, .t509, .t511, .t517, .t518, .t519, .t520, .t532, .t533, .t538, .t539, .t544, .t545, .t552, .t554, .t569, .t570, .t577, .t592, .t598, .t599, .t601, .t604, .t605, .t609, .t615, .t616, .t650, .t659, .t670, .t675, .t686, .t688, .t694, .t698, .t700, .t726, .t728, .t730, .t734, .t738, .t740, .t744, .t754, .t760, .t762, .t764, .t774, .t776, .t778, .t780, .t786, .t798, .t799, .t801, .t813, .t814, .t822, .t826, .t827, .t829, .t842, .t843, .t849, .t850, .t851, .t856, .t858, .t859, .t860, .t881, .t889, .t902, .t912, .t923, .t937, .t958, .t959, .t979, .t982, .t983, .t989, .t994, .t1067, .t1068, .t1069, .t1070, .t1071, .t1072, .t1053');Array.prototype.forEach.call(currentRecChildren,function(child){child.dispatchEvent(event)});var displayChangedBlock=currentRec.querySelector('[data-display-changed="true"]');if(displayChangedBlock)displayChangedBlock.dispatchEvent(event)});var galaxyEffectBlocks=document.querySelectorAll('.t826');Array.prototype.forEach.call(galaxyEffectBlocks,function(galaxyEffectBlock){galaxyEffectBlock.dispatchEvent(event)});if(window.lazy==='y'||tildaLazyMode==='yes'){t_onFuncLoad('t_lazyload_update',function(){t_lazyload_update()})}}
function t397_showActiveTabFromKeyboard(recid,currentIndex,tabs){var rec=document.querySelector('#rec'+recid);var currentTab=rec.querySelector('[data-tab-number="'+currentIndex+'"]');if(!currentTab)return;var currentButton=currentTab.querySelector('.t397__title');if(currentButton){currentButton.focus()}
var tabList=rec.querySelector('.t397__wrapper');if(tabList)tabList.setAttribute('data-tab-current',currentIndex)}
function t397_alltabs_updateContent(recid){var rec=document.getElementById('rec'+recid);if(!rec)return;var tabs=Array.prototype.slice.call(rec.querySelectorAll('.t397__tab:not(.t397__tab_active)'));var activeTab=rec.querySelector('.t397__tab_active');var select=rec.querySelector('.t397__select');if(!activeTab)return;var hookBlocks=activeTab.getAttribute('data-tab-rec-ids').split(',');var noActive=[];var popupBlocks=[190,217,312,331,358,364,365,390,702,706,746,750,756,768,862,868,890,945,1013,1014];Array.prototype.forEach.call(tabs,function(tab){if(tab!==activeTab){var noActiveHooks=tab.getAttribute('data-tab-rec-ids').split(',');noActiveHooks.forEach(function(hook){if(noActive.indexOf(hook)===-1&&hookBlocks.indexOf(hook)===-1)noActive.push(hook);var tabBlock=document.getElementById('rec'+hook);if(tabBlock&&(tabBlock.getAttribute('data-record-type')==397||tabBlock.getAttribute('data-record-type')==395)){var activeTab=tabBlock.querySelector('.t397__tab_active, .t395__tab_active');if(activeTab){var noActiveSubHooks=activeTab.getAttribute('data-tab-rec-ids').split(',');noActiveSubHooks.forEach(function(subhook){if(noActive.indexOf(subhook)===-1&&hookBlocks.indexOf(subhook)===-1)noActive.push(subhook)})}}})}});if(t397_checkVisibillityEl(activeTab)||t397_checkVisibillityEl(select)){hookBlocks.forEach(function(hook){if(!hook)return;var hookEl=document.getElementById('rec'+hook);var hookElRecordType=hookEl?hookEl.getAttribute('data-record-type'):'';if(hookEl){hookEl.classList.remove('t397__off');hookEl.classList.remove('t395__off');hookEl.setAttribute('aria-hidden',!1);hookEl.style.opacity=''}
t397_updateTabsByHook(hookElRecordType,hookEl,hook,recid)})}else{hookBlocks.forEach(function(hook){var hookEl=document.getElementById('rec'+hook);var hookElRecordType=hookEl?hookEl.getAttribute('data-record-type'):'';var isPopupBlock=popupBlocks.some(function(id){return hookElRecordType==id});if(hookEl&&!isPopupBlock){hookEl.setAttribute('data-animationappear','off');hookEl.classList.add('t397__off');hookEl.setAttribute('aria-hidden',!0)}
t397_updateTabsByHook(hookElRecordType,hookEl,hook,recid)})}
noActive.forEach(function(noActiveID){if(!noActiveID)return;var hookEl=document.getElementById('rec'+noActiveID);var hookElRecordType=hookEl?hookEl.getAttribute('data-record-type'):'';var isPopupBlock=popupBlocks.some(function(id){return hookElRecordType==id});if(hookEl&&!isPopupBlock){hookEl.setAttribute('data-connect-with-tab','yes');hookEl.setAttribute('data-animationappear','off');hookEl.classList.add('t397__off');hookEl.setAttribute('aria-hidden',!0)}
t397_updateTabsByHook(hookElRecordType,hookEl,noActiveID,recid)});var scrollHeight=Math.max(document.body.scrollHeight,document.documentElement.scrollHeight,document.body.offsetHeight,document.documentElement.offsetHeight,document.body.clientHeight,document.documentElement.clientHeight);if(scrollHeight-window.innerHeight<window.pageYOffset){window.scrollTo(0,scrollHeight-window.innerHeight)}}
function t397_updateTabsByHook(hookElRecordType,hookEl,currentID,recid){var hookElTab;switch(hookElRecordType){case '395':if(window.t395_alltabs_updateContent&&window.t395_updateSelect&&recid!==currentID){window.t395_alltabs_updateContent(currentID);window.t395_updateSelect(currentID);hookElTab=hookEl?hookEl.querySelector('.t395__tab'):null;if(hookElTab)hookElTab.click()}
break;case '397':if(recid!==currentID){t397_alltabs_updateContent(currentID);t397_updateSelect(currentID);hookElTab=hookEl?hookEl.querySelector('.t397__tab'):null;if(hookElTab)hookElTab.click()}
break}}
function t397_checkVisibillityEl(el){return!!(el&&(el.offsetWidth||el.offsetHeight||el.getClientRects().length))}
function t397_updateContentBySelect(recid){var rec=document.getElementById('rec'+recid);if(!rec)return!1;var select=rec.querySelector('.t397__select');if(select){select.addEventListener('change',function(){var tabIndex=rec.querySelector('.t397__tab[data-tab-rec-ids=\''+select.value+'\'][data-tab-index="'+select.selectedIndex+'"]');if(tabIndex)tabIndex.click()})}}
function t397_updateSelect(recid){var rec=document.getElementById('rec'+recid);if(!rec)return!1;var activeTab=rec.querySelector('.t397__tab_active');var currentTabHooks=activeTab?activeTab.getAttribute('data-tab-index'):'';var select=rec.querySelector('.t397__select');if(select)select.selectedIndex=currentTabHooks}
function t397_scrollToTabs(recid,hash){var rec=document.getElementById('rec'+recid);var curUrl=hash||decodeURI(window.location.href);var tabIndexNumber=curUrl.indexOf('#!/tab/');if(tabIndexNumber===-1)return!1;var tabIndexNumberStart=curUrl.indexOf('tab/');var firstOptionSelect=rec?rec.querySelector('.t397__wrapper_mobile .t397__select option'):null;if(firstOptionSelect)firstOptionSelect.selected=!1;var tabRec=curUrl.substring(tabIndexNumberStart+4,tabIndexNumberStart+4+recid.length);if(tabRec!==recid)return!1;var tabBlock=rec?rec.querySelector('.t397'):null;var tabNumber=parseInt(curUrl.slice(tabIndexNumberStart+4+recid.length+1),10);var tabs=rec.querySelectorAll('.t397__tab');Array.prototype.forEach.call(tabs,function(tab,i){if(i===tabNumber-1){tab.click();tab.classList.add('t397__tab_active')}else{tab.classList.remove('t397__tab_active')}});var tabsMob=rec.querySelectorAll('.t397__wrapper_mobile .t397__select option');var activeTabMob=tabsMob.length?tabsMob[tabNumber-1]:null;if(activeTabMob)activeTabMob.selected=!0;setTimeout(function(){t397_scrollToEl(tabBlock)},50)}
function t397_scrollToEl(el){function getElTopPos(){var elTopPos=el.getBoundingClientRect().top+window.pageYOffset;elTopPos=window.innerWidth>960?elTopPos-200:elTopPos-100;if(elTopPos<0)elTopPos=0;var documentHeight=Math.max(document.body.scrollHeight,document.documentElement.scrollHeight,document.body.offsetHeight,document.documentElement.offsetHeight,document.body.clientHeight,document.documentElement.clientHeight);var bottomViewportPoint=documentHeight-document.documentElement.clientHeight;if(elTopPos>bottomViewportPoint)elTopPos=bottomViewportPoint;return elTopPos}
var startPosition=window.pageYOffset;var startTime=null;var duration=300;function scrollAnimation(currentTime){if(startTime===null)startTime=currentTime;var timeElapsed=currentTime-startTime;var elTopPos=getElTopPos();var distance=elTopPos-startPosition;var run=easeInQuad(timeElapsed,startPosition,distance,duration);window.scrollTo(0,run);document.body.setAttribute('data-scrollable','true');if(timeElapsed<duration){requestAnimationFrame(scrollAnimation)}else{window.scrollTo(0,elTopPos);document.body.removeAttribute('data-scrollable')}}
function easeInQuad(timeElapsed,startPosition,distance,duration){timeElapsed/=duration;return distance*timeElapsed*timeElapsed+startPosition}
requestAnimationFrame(scrollAnimation)}
function t397_removeUrl(){var curUrl=window.location.href;var indexToRemove=curUrl.indexOf('#!/tab/');if(indexToRemove===-1){indexToRemove=curUrl.indexOf('%23!/tab/')}
curUrl=curUrl.substring(0,indexToRemove);if(indexToRemove!==-1){if(typeof history.replaceState!='undefined'){try{window.history.replaceState('','',curUrl)}catch(err){}}}}
function t849_init(recId){var rec=document.getElementById('rec'+recId);if(!rec)return;var togglers=rec.querySelectorAll('.t849__header');var isLazy=document.getElementById('allrecords').getAttribute('data-tilda-lazy');var accordion=rec.querySelector('.t849__accordion');if(accordion){accordion=accordion.getAttribute('data-accordion')}else{accordion='false'}
var cachedHeight=0;var cachedTop=0;Array.prototype.forEach.call(togglers,function(toggler){toggler.addEventListener('click',function(){var target=toggler;var content=target.nextElementSibling;var triggerButton=target.querySelector('.t849__trigger-button');if(accordion==='true'){Array.prototype.forEach.call(togglers,function(header){if(target!==header){header.classList.remove('t849__opened');t849_slideUp(header.nextElementSibling,target)}})}
if(triggerButton){var isExpanded=triggerButton.getAttribute('aria-expanded')==='true';triggerButton.setAttribute('aria-expanded',!isExpanded);content.hidden=isExpanded}
target.classList.toggle('t849__opened');target.style.pointerEvents='none';t849_slideToggle(target.nextElementSibling,target);if(window.lazy==='y'||isLazy==='yes'){t_onFuncLoad('t_lazyload_update',function(){t_lazyload_update()})}})});function t849_slideToggle(target,triggerElement,duration){if(!target)return;if(!duration&&duration!==0)duration=300;if(window.getComputedStyle(target).display==='none'){return t849_slideDown(target,triggerElement,duration)}else{cachedHeight=0;return t849_slideUp(target,triggerElement,duration)}}
function t849_slideUp(target,triggerElement,duration){if(!target)return;if(!duration&&duration!==0)duration=300;target.style.transitionProperty='height, margin, padding';target.style.transitionDuration=duration+'ms';target.style.boxSizing='border-box';target.style.height=target.offsetHeight+'px';target.offsetHeight;target.style.overflow='hidden';target.style.height='0';target.style.paddingTop='0';target.style.paddingBottom='0';target.style.marginTop='0';target.style.marginBottom='0';setTimeout(function(){triggerElement.style.pointerEvents='auto';target.style.display='none';target.style.height='';target.style.paddingTop='';target.style.paddingBottom='';target.style.marginTop='';target.style.marginBottom='';target.style.overflow='';target.style.transitionDuration='';target.style.transitionProperty=''},duration)}
function t849_slideDown(target,triggerElement,duration){if(!target)return;if(!duration&&duration!==0)duration=300;target.style.display='';var cashedDisplay=window.getComputedStyle(target).display;if(cashedDisplay==='none')cashedDisplay='block';target.style.display=cashedDisplay;var targetHeight=target.offsetHeight;var targetTop=target.offsetTop;if(window.visualViewport){var visibleTop=targetTop-window.visualViewport.pageTop;if(cachedTop&&accordion==='true'&&targetTop>cachedTop&&window.scrollY>cachedTop){window.scrollTo(window.scrollX,targetTop-cachedHeight-visibleTop)}}
target.style.overflow='hidden';target.style.height='0';target.style.paddingTop='0';target.style.paddingBottom='0';target.style.marginTop='0';target.style.marginBottom='0';target.offsetHeight;target.style.boxSizing='border-box';target.style.transitionProperty='height, margin, padding';target.style.transitionDuration=duration+'ms';target.style.height=targetHeight+'px';target.style.paddingTop='';target.style.paddingBottom='';target.style.marginTop='';target.style.marginBottom='';setTimeout(function(){triggerElement.style.pointerEvents='auto';target.style.height='';target.style.overflow='';target.style.transitionDuration='';target.style.transitionProperty='';cachedHeight=targetHeight;cachedTop=targetTop},duration)}}
function t142_checkSize(recId){var rec=document.getElementById('rec'+recId);if(!rec)return;var button=rec.querySelector('.t142__submit');if(!button)return;var buttonStyle=getComputedStyle(button,null);var buttonPaddingTop=parseInt(buttonStyle.paddingTop)||0;var buttonPaddingBottom=parseInt(buttonStyle.paddingBottom)||0;var buttonHeight=button.clientHeight-(buttonPaddingTop+buttonPaddingBottom)+5;var textHeight=button.scrollHeight;if(buttonHeight<textHeight){button.classList.add('t142__submit-overflowed')}}
function t959__init(recId){var rec=document.getElementById('rec'+recId);if(!rec)return;var container=rec.querySelector('.t959');if(!container)return;t959__updateLazyLoad(recId);t959_unifyHeights(recId);window.addEventListener('resize',t_throttle(function(){t959_unifyHeights(recId)}));window.addEventListener('load',function(){t959_unifyHeights(recId)});container.addEventListener('displayChanged',t_throttle(function(){t959_unifyHeights(recId)}));t_onFuncLoad('t_card__moveClickOnCard',function(){t_card__moveClickOnCard(recId)});t_onFuncLoad('t_card__addFocusOnTab',function(){t_card__addFocusOnTab(recId)})}
function t959__updateLazyLoad(recId){var allRecords=document.getElementById('allrecords');var container=document.querySelector('#rec'+recId+' .t959__container_mobile-flex');var mode=allRecords.getAttribute('data-tilda-mode');if(container&&mode!=='edit'&&mode!=='preview'&&window.isMobile){if(window.lazy==='y'||allRecords.getAttribute('data-tilda-lazy')==='yes'){t_onFuncLoad('t_lazyload_update',function(){container.addEventListener('touchmove',t_throttle(function(){t_lazyload_update()}))})}}}
function t959_unifyHeights(recId){var rec=document.getElementById('rec'+recId);if(!rec)return;var main=rec.querySelector('.t959');if(!main)return;var containers=main.querySelectorAll('.t959__container');for(var i=0;i<containers.length;i++){var container=containers[i];var cardsContent=container.querySelectorAll('.t959__card-content');var cards=container.querySelectorAll('.t959__card-inner');if(!cards.length){return}
var cardStyle=getComputedStyle(cards[0],null);var cardPaddingLeft=parseInt(cardStyle.paddingLeft)||0;var cardPaddingRight=parseInt(cardStyle.paddingRight)||0;var cardWidth=cards[0].clientWidth-(cardPaddingLeft+cardPaddingRight);var maxHeight=0;var ratio=container.getAttribute('data-ratio');var minHeightFromRatio=0;switch(ratio){case '16_9':minHeightFromRatio=cardWidth*0.5625;break;case '4_3':minHeightFromRatio=cardWidth*0.75;break;case '3_2':minHeightFromRatio=cardWidth*0.6666;break;case '1_1':minHeightFromRatio=cardWidth;break;case '2_3':minHeightFromRatio=cardWidth*1.5;break;case '3_4':minHeightFromRatio=cardWidth*1.3333;break;case '9_16':minHeightFromRatio=cardWidth*1.7777;break}
for(var j=0;j<cardsContent.length;j++){var cardContent=cardsContent[j];var titleHeight=t959_outerHeight(cardContent.querySelector('.t-card__title'));var descHeight=t959_outerHeight(cardContent.querySelector('.t-card__descr'));var colHeight=titleHeight+descHeight;if(colHeight>maxHeight)maxHeight=colHeight}
if(maxHeight>minHeightFromRatio){for(var j=0;j<cards.length;j++){cards[j].style.paddingBottom=maxHeight+'px'}}else{for(var j=0;j<cards.length;j++){cards[j].style.paddingBottom=null}}}}
function t959_outerHeight(element){if(!element)return 0;var height=element.offsetHeight;var style=getComputedStyle(element);height+=parseInt(style.marginTop)+parseInt(style.marginBottom);return height}
function t450_showMenu(recid){var rec=document.getElementById('rec'+recid);if(!rec)return;var menu=rec.querySelector('.t450');var overlay=rec.querySelector('.t450__overlay');var menuElements=rec.querySelectorAll('.t450__overlay, .t450__close, a[href*="#"]');if(typeof t_triggerEvent==='function')t_triggerEvent(document.body,'popupShowed');document.body.classList.add('t450__body_menushowed');if(menu)menu.classList.add('t450__menu_show');if(overlay)overlay.classList.add('t450__menu_show');if(menu){menu.addEventListener('clickedAnchorInTooltipMenu',function(){t450_closeMenu(menu,overlay)})}
Array.prototype.forEach.call(menuElements,function(element){element.addEventListener('click',function(){if(element.closest('.tooltipstered, .t-menusub__target-link, .t794__tm-link, .t966__tm-link, .t978__tm-link'))return;if(element.href&&(element.href.substring(0,7)==='#price:'||element.href.substring(0,9)==='#submenu:'))return;t450_closeMenu(menu,overlay)})});document.addEventListener('keydown',function(e){if(e.keyCode===27){document.body.classList.remove('t390__body_popupshowed');var popups=document.querySelectorAll('.t390');Array.prototype.forEach.call(popups,function(popup){popup.classList.remove('t390__popup_show')})}});rec.addEventListener('click',function(e){if(e.target.closest('.t966__tm-link, .t978__tm-link')){t450_checkSize(recid);if(e.target.closest('.t978__tm-link')){setTimeout(function(){var hookLink=e.target.closest('.t978__tm-link');var menuBlock=hookLink.nextElementSibling;var submenuLinks=menuBlock?menuBlock.querySelectorAll('.t978__menu-link'):[];Array.prototype.forEach.call(submenuLinks,function(link){link.addEventListener('click',function(){t450_checkSize(recid)})})},300)}}});menu.addEventListener('menuOverflow',function(){t450_checkSize(recid)});t450_highlight(recid)}
function t450_closeMenu(menu,overlay){if(typeof t_triggerEvent==='function')t_triggerEvent(document.body,'popupHidden');document.body.classList.remove('t450__body_menushowed');if(menu)menu.classList.remove('t450__menu_show');if(overlay)overlay.classList.remove('t450__menu_show')}
function t450_checkSize(recid){var rec=document.getElementById('rec'+recid);var menu=rec?rec.querySelector('.t450'):null;if(!menu)return;var container=menu.querySelector('.t450__container');var topContainer=menu.querySelector('.t450__top');var rightContainer=menu.querySelector('.t450__rightside');setTimeout(function(){var topContainerHeight=topContainer?topContainer.offsetHeight:0;var rightContainerHeight=rightContainer?rightContainer.offsetHeight:0;var containerPaddingTop=container?window.getComputedStyle(container).paddingTop:'0';var containerPaddingBottom=container?window.getComputedStyle(container).paddingBottom:'0';containerPaddingTop=parseInt(containerPaddingTop,10);containerPaddingBottom=parseInt(containerPaddingBottom,10);if(topContainerHeight+rightContainerHeight+containerPaddingTop+containerPaddingBottom>document.documentElement.clientHeight){menu.classList.add('t450__overflowed')}else{menu.classList.remove('t450__overflowed')}})}
function t450_appearMenu(recid){var rec=document.getElementById('rec'+recid);var burger=rec?rec.querySelector('.t450__menu__content'):null;if(!burger)return;var burgerAppearOffset=burger?burger.getAttribute('data-appearoffset'):'';var burgerHideOffset=burger?burger.getAttribute('data-hideoffset'):'';if(burgerAppearOffset){burgerAppearOffset=t450_appearMenuParseNumber(burgerAppearOffset);if(window.pageYOffset>=burgerAppearOffset){if(burger.classList.contains('t450__beforeready')){burger.classList.remove('t450__beforeready')}}else{burger.classList.add('t450__beforeready')}}
if(burgerHideOffset){burgerHideOffset=t450_appearMenuParseNumber(burgerHideOffset);var scrollHeight=Math.max(document.body.scrollHeight,document.documentElement.scrollHeight,document.body.offsetHeight,document.documentElement.offsetHeight,document.body.clientHeight,document.documentElement.clientHeight);if(window.pageYOffset+window.innerHeight>=scrollHeight-burgerHideOffset){if(!burger.classList.contains('t450__beforeready')){burger.classList.add('t450__beforeready')}}else if(burgerAppearOffset){if(window.pageYOffset>=burgerAppearOffset){burger.classList.remove('t450__beforeready')}}else{burger.classList.remove('t450__beforeready')}}}
function t450_appearMenuParseNumber(string){if(string.indexOf('vh')>-1){string=Math.floor((window.innerHeight*(parseInt(string)/100)))}
return parseInt(string,10)}
function t450_initMenu(recid){var rec=document.getElementById('rec'+recid);var menu=rec?rec.querySelector('.t450'):null;var overlay=rec?rec.querySelector('.t450__overlay'):null;var burger=rec?rec.querySelector('.t450__burger_container'):null;var menuLinks=rec?rec.querySelectorAll('.t-menu__link-item.t450__link-item_submenu'):[];var hook=menu?menu.getAttribute('data-tooltip-hook'):'';if(hook){document.addEventListener('click',function(e){if(e.target.closest('a[href="'+hook+'"]')){e.preventDefault();t450_closeMenu(menu,overlay);t450_showMenu(recid);t450_checkSize(recid)}})}
if(burger){burger.addEventListener('click',function(){t450_closeMenu(menu,overlay);t450_showMenu(recid);t450_checkSize(recid)})}
window.addEventListener('resize',function(){t450_checkSize(recid)});if(!window.isMobile)return;Array.prototype.forEach.call(menuLinks,function(link){link.addEventListener('click',function(){t450_checkSize(recid)})})}
function t450_highlight(recid){var url=window.location.href;var pathname=window.location.pathname;var hash=window.location.hash;if(url.substr(url.length-1)==='/'){url=url.slice(0,-1)}
if(pathname.substr(pathname.length-1)==='/'){pathname=pathname.slice(0,-1)}
if(pathname.charAt(0)==='/'){pathname=pathname.slice(1)}
if(pathname===''){pathname='/'}
var shouldBeActiveElements=document.querySelectorAll('.t450__menu a[href=\''+url+'\'], '+'.t450__menu a[href=\''+url+'/\'], '+'.t450__menu a[href=\''+pathname+'\'], '+'.t450__menu a[href=\'/'+pathname+'\'], '+'.t450__menu a[href=\''+pathname+'/\'], '+'.t450__menu a[href=\'/'+pathname+'/\']'+(hash?', .t450__menu a[href=\''+hash+'\']':''));var rec=document.getElementById('rec'+recid);var menuLinks=rec?rec.querySelectorAll('.t450__menu a'):[];Array.prototype.forEach.call(menuLinks,function(link){if(link.getAttribute('data-highlighted-by-user')!=='y')link.classList.remove('t-active')});Array.prototype.forEach.call(shouldBeActiveElements,function(link){link.classList.add('t-active')})}
function t794_init(recid){var rec=document.getElementById('rec'+recid);var menu=rec?rec.querySelector('.t794'):null;var hook=menu?menu.getAttribute('data-tooltip-hook'):'';if(!hook)return;var hookLinks=document.querySelectorAll('a[href="'+hook+'"]');hookLinks=Array.prototype.filter.call(hookLinks,function(hookLink){var isSubmenuAllowed=hookLink.getAttribute('data-submenu-disallowed')!=='yes';if(isSubmenuAllowed){hookLink.classList.add('t794__tm-link');hookLink.setAttribute('data-tooltip-menu-id',recid);return!0}
return!1});var parentMenu=hookLinks.length?hookLinks[0].closest('[data-menu]'):null;var tooltipMenu=rec.querySelector('.t794__tooltip-menu');var isParentFixed=parentMenu&&window.getComputedStyle(parentMenu).position==='fixed';if(tooltipMenu)tooltipMenu.setAttribute('data-pos-fixed',isParentFixed?'yes':'no');t794_addArrow(recid,hookLinks);t794_setUpMenu(recid,hookLinks);t_onFuncLoad('t_submenublocks__highlightActiveLinks',function(){t_submenublocks__highlightActiveLinks('.t794__list_item a')});if(menu.hasAttribute('data-full-submenu-mob')&&(window.isMobile||'ontouchend' in document)){t_onFuncLoad('t_submenublocks__setFullScreenMenu',function(){t_submenublocks__setFullScreenMenu(menu)})}}
function t794_addArrow(recid,hookLinks){var rec=document.getElementById('rec'+recid);var submenuBlock=rec?rec.querySelector('.t794'):null;var isArrowAppend=submenuBlock.getAttribute('data-add-arrow');if(!isArrowAppend)return;hookLinks=Array.prototype.slice.call(hookLinks);hookLinks.forEach(function(hookLink){var arrow=document.createElement('div');arrow.classList.add('t794__arrow');hookLink.appendChild(arrow);var isInsideZero=hookLink.closest('.tn-atom');var hasCustomBorderColor=window.getComputedStyle(hookLink).borderColor!=='rgba(0, 0, 0, 0)';if(isInsideZero&&!hasCustomBorderColor){hookLink.style.borderColor='initial';hookLink.style.border='none'}})}
function t794_setUpMenu(recid,hookLinks){var rec=document.getElementById('rec'+recid);var submenu=rec?rec.querySelector('.t794__tooltip-menu'):null;if(!submenu)return;var menuBlock=rec?rec.querySelector('.t794'):null;var verticalIndent=menuBlock.getAttribute('data-tooltip-margin');var content=submenu.querySelector('.t794__content');var hooksAndSubmenu=hookLinks.concat(submenu);if(window.innerWidth>980&&!('ontouchend' in document)){t_onFuncLoad('t_submenublocks__addEventsDesktop',function(){t_submenublocks__addEventsDesktop(submenu,hooksAndSubmenu,verticalIndent,'.t794')})}else{t_onFuncLoad('t_submenublocks__addEventsMobile',function(){t_submenublocks__addEventsMobile(submenu,hookLinks,verticalIndent,'.t794')})}
window.addEventListener('scroll',t_throttle(function(){if(content){content.addEventListener('mouseleave',function(){if(submenu.classList.contains('t794__tooltip-menu_show')){t_onFuncLoad('t_submenublocks__hideSubmenu',function(){t_submenublocks__hideSubmenu(submenu,'.t794')})}})}},300));var tooltipLinks=document.querySelectorAll('.t794__tooltip-menu a[href*="#"]');Array.prototype.forEach.call(tooltipLinks,function(tooltipLink){tooltipLink.addEventListener('click',function(){t_onFuncLoad('t_submenublocks__hideSubmenu',function(){t_submenublocks__hideSubmenu(submenu,'.t794')});var menuList=document.querySelectorAll('.t450, .t199__mmenu, .t280, .t282, .t204__burger, .t451, .t466');Array.prototype.forEach.call(menuList,function(menu){var event=document.createEvent('Event');event.initEvent('clickedAnchorInTooltipMenu',!0,!0);menu.dispatchEvent(event)});Array.prototype.forEach.call(tooltipLinks,function(link){link.classList.remove('t-active')});tooltipLink.classList.add('t-active')})})}
function t481_setWidth(recid){if(window.innerWidth<=980)return;var menuBlocks=document.querySelectorAll('.t481');Array.prototype.forEach.call(menuBlocks,function(menu){var alignment=menu.getAttribute('data-menu-items-align');var leftContainer=menu.querySelector('.t481__leftcontainer');var rightContainer=menu.querySelector('.t481__rightcontainer');var centerContainer=menu.querySelector('.t481__centercontainer');var mainContainer=menu.querySelector('.t481__maincontainer');var centerContainerList=centerContainer?centerContainer.querySelectorAll('li'):[];var maxWidth=Math.max(t481_getFullWidth(leftContainer),t481_getFullWidth(rightContainer));maxWidth=Math.ceil(maxWidth);var paddingWidth=40;var centerWidth=0;Array.prototype.forEach.call(centerContainerList,function(list){centerWidth+=t481_getFullWidth(list)});var leftSide=menu.querySelector('.t481__leftside');var rightSide=menu.querySelector('.t481__rightside');var mainContainerWidth=t481_getFullWidth(mainContainer);if(mainContainerWidth-(maxWidth*2+paddingWidth*2)>centerWidth+20){if(alignment==='center'||!alignment){if(leftSide)leftSide.style.minWidth=maxWidth+'px';if(rightSide)rightSide.style.minWidth=maxWidth+'px'}}else{if(leftSide)leftSide.style.minWidth='';if(rightSide)rightSide.style.minWidth=''}})}
function t481_getFullWidth(element){if(!element)return 0;var marginLeft=element.style.marginLeft||window.getComputedStyle(element).marginLeft;var marginRight=element.style.marginRight||window.getComputedStyle(element).marginRight;marginLeft=parseInt(marginLeft,10)||0;marginRight=parseInt(marginRight,10)||0;return element.offsetWidth+marginLeft+marginRight}
function t975_init(recid){var rec=document.getElementById('rec'+recid);if(!rec)return;var tildaCopy=document.getElementById('tildacopy');var menu=rec.querySelector('.t975');t_onFuncLoad('t_menu__highlightActiveLinks',function(){t_menu__highlightActiveLinks('.t975__list-item a')});if(menu)menu.classList.remove('t975__beforeready');t975_checkAnchorLinks(recid,'.t975__list-item a');var isIphone=t975_detectIphone();var scrollHeight=Math.max(document.body.scrollHeight,document.documentElement.scrollHeight,document.body.offsetHeight,document.documentElement.offsetHeight,document.body.clientHeight,document.documentElement.clientHeight);if(menu&&menu.getAttribute('data-hidemenuonscroll')||isIphone){t975_handleScroll(menu,tildaCopy)}
if(tildaCopy&&scrollHeight>document.documentElement.clientHeight){t975_addCopyrightMargin(menu,tildaCopy);t975_handleScroll(menu,tildaCopy)}
window.addEventListener('resize',function(){t975_changeCopyrightMargin(menu,tildaCopy)})}
function t975_addCopyrightMargin(menu,tildaCopy){if(!tildaCopy||!menu)return;var paddingElement=document.createElement('div');paddingElement.style.backgroundColor='#000';paddingElement.style.height=menu.offsetHeight+'px';paddingElement.classList.add('t-tildalabel-padding');document.body.appendChild(paddingElement)}
function t975_changeCopyrightMargin(menu,tildaCopy){var paddingElement=document.querySelector('.t-tildalabel-padding');if(!paddingElement||!tildaCopy||!menu)return;paddingElement.style.height=menu.offsetHeight+'px'}
function t975_detectIphone(){var isIphone=/iPhone/.test(navigator.userAgent)&&!window.MSStream;var aspect=window.screen.width/window.screen.height;var iphoneAspect='0.462';if(isIphone&&aspect.toFixed(3)===iphoneAspect){return!0}}
function t975_checkAnchorLinks(recid,selector){var rec=document.getElementById('rec'+recid);var anchorSelector=selector+'[href*="#"]:not(.tooltipstered)';var navLinks=rec?rec.querySelectorAll(anchorSelector):[];if(navLinks.length){t_onFuncLoad('t_menu__updateActiveLinks',function(){t_menu__updateActiveLinks(navLinks,selector)})}}
function t975_handleScroll(menu){var lastScrollTop=0;var delta=5;var timerID;var diff;window.addEventListener('scroll',function(){var scrollHeight=Math.max(document.body.scrollHeight,document.documentElement.scrollHeight,document.body.offsetHeight,document.documentElement.offsetHeight,document.body.clientHeight,document.documentElement.clientHeight);var isClicked=menu?menu.getAttribute('data-clicked-link'):'';var currentScrollTop=window.pageYOffset;if(Math.abs(lastScrollTop-currentScrollTop)<=delta||window.pageYOffset<0||window.pageYOffset>scrollHeight-window.innerHeight){return}
if(menu&&menu.getAttribute('data-hidemenuonscroll')&&!isClicked){var menuHeight=menu.offsetHeight;var currentTransformValue=menu.style.transform;if(currentScrollTop>lastScrollTop&&window.pageYOffset<=scrollHeight-(window.innerHeight+menuHeight)){diff=0;if(currentTransformValue){diff=parseInt(currentTransformValue.replace('translateY(',''),10)}
clearInterval(timerID);timerID=setInterval(function(){menu.style.transform='translateY('+diff+'px)';diff+=menuHeight/50;if(diff>=menuHeight){menu.style.transform='translateY('+menuHeight+'px)';clearInterval(timerID)}})}else{diff=menuHeight;if(currentTransformValue){diff=parseInt(currentTransformValue.replace('translateY(',''),10)}
clearInterval(timerID);timerID=setInterval(function(){menu.style.transform='translateY('+diff+'px)';diff-=menuHeight/50;if(diff<=0){menu.style.transform='translateY(0px)';clearInterval(timerID)}})}}
lastScrollTop=currentScrollTop})}
function t702_initPopup(recId){var rec=document.getElementById('rec'+recId);if(!rec)return;var container=rec.querySelector('.t702');if(!container)return;rec.setAttribute('data-animationappear','off');rec.setAttribute('data-popup-subscribe-inited','y');rec.style.opacity=1;var documentBody=document.body;var popup=rec.querySelector('.t-popup');var popupTooltipHook=popup.getAttribute('data-tooltip-hook');var analitics=popup.getAttribute('data-track-popup');var popupCloseBtn=popup.querySelector('.t-popup__close');var hrefs=rec.querySelectorAll('a[href*="#"]');var submitHref=rec.querySelector('.t-submit[href*="#"]');if(popupTooltipHook){t_onFuncLoad('t_popup__addAttributesForAccessibility',function(){t_popup__addAttributesForAccessibility(popupTooltipHook)});document.addEventListener('click',function(event){var target=event.target;var href=target.closest('a[href$="'+popupTooltipHook+'"]')?target:!1;if(!href)return;event.preventDefault();t702_showPopup(recId);t_onFuncLoad('t_popup__resizePopup',function(){t_popup__resizePopup(recId)});t702__lazyLoad();if(analitics&&window.Tilda){Tilda.sendEventToStatistics(analitics,popupTooltipHook)}});t_onFuncLoad('t_popup__addClassOnTriggerButton',function(){t_popup__addClassOnTriggerButton(document,popupTooltipHook)})}
popup.addEventListener('scroll',t_throttle(function(){t702__lazyLoad()}));popup.addEventListener('click',function(event){var windowWithoutScrollBar=window.innerWidth-17;if(event.clientX>windowWithoutScrollBar)return;if(event.target===this)t702_closePopup(recId)});popupCloseBtn.addEventListener('click',function(){t702_closePopup(recId)});if(submitHref){submitHref.addEventListener('click',function(){if(documentBody.classList.contains('t-body_scroll-locked')){documentBody.classList.remove('t-body_scroll-locked')}})}
for(var i=0;i<hrefs.length;i++){hrefs[i].addEventListener('click',function(){var url=this.getAttribute('href');if(!url||url.substring(0,7)!='#price:'){t702_closePopup(recId);if(!url||url.substring(0,7)=='#popup:'){setTimeout(function(){if(typeof t_triggerEvent==='function')t_triggerEvent(document.body,'popupShowed');documentBody.classList.add('t-body_popupshowed')},300)}}})}
function t702_escClosePopup(event){if(event.key==='Escape')t702_closePopup(recId)}
popup.addEventListener('tildamodal:show'+popupTooltipHook,function(){document.addEventListener('keydown',t702_escClosePopup)});popup.addEventListener('tildamodal:close'+popupTooltipHook,function(){document.removeEventListener('keydown',t702_escClosePopup)})}
function t702_lockScroll(){var documentBody=document.body;if(!documentBody.classList.contains('t-body_scroll-locked')){var bodyScrollTop=typeof window.pageYOffset!=='undefined'?window.pageYOffset:(document.documentElement||documentBody.parentNode||documentBody).scrollTop;documentBody.classList.add('t-body_scroll-locked');documentBody.style.top='-'+bodyScrollTop+'px';documentBody.setAttribute('data-popup-scrolltop',bodyScrollTop)}}
function t702_unlockScroll(){var documentBody=document.body;if(documentBody.classList.contains('t-body_scroll-locked')){var bodyScrollTop=documentBody.getAttribute('data-popup-scrolltop');documentBody.classList.remove('t-body_scroll-locked');documentBody.style.top=null;documentBody.removeAttribute('data-popup-scrolltop');document.documentElement.scrollTop=parseInt(bodyScrollTop)}}
function t702_showPopup(recId){var rec=document.getElementById('rec'+recId);if(!rec)return;var container=rec.querySelector('.t702');if(!container)return;var windowWidth=window.innerWidth;var screenMin=rec.getAttribute('data-screen-min');var screenMax=rec.getAttribute('data-screen-max');if(screenMin&&windowWidth<parseInt(screenMin,10))return;if(screenMax&&windowWidth>parseInt(screenMax,10))return;var popup=rec.querySelector('.t-popup');var popupTooltipHook=popup.getAttribute('data-tooltip-hook');var ranges=rec.querySelectorAll('.t-range');var documentBody=document.body;if(ranges.length){Array.prototype.forEach.call(ranges,function(range){t702__triggerEvent(range,'popupOpened')})}
t_onFuncLoad('t_popup__showPopup',function(){t_popup__showPopup(popup)});if(typeof t_triggerEvent==='function')t_triggerEvent(document.body,'popupShowed');documentBody.classList.add('t-body_popupshowed');documentBody.classList.add('t702__body_popupshowed');if(/iPhone|iPad|iPod/i.test(navigator.userAgent)&&!window.MSStream&&window.isiOSVersion&&window.isiOSVersion[0]===11){setTimeout(function(){t702_lockScroll()},500)}
t702__lazyLoad();t702__triggerEvent(popup,'tildamodal:show'+popupTooltipHook);t_onFuncLoad('t_forms__calculateInputsWidth',function(){t_forms__calculateInputsWidth(recId)})}
function t702_closePopup(recId){var rec=document.getElementById('rec'+recId);var popup=rec.querySelector('.t-popup');var popupTooltipHook=popup.getAttribute('data-tooltip-hook');var popupAll=document.querySelectorAll('.t-popup_show:not(.t-feed__post-popup):not(.t945__popup)');if(popupAll.length==1){if(typeof t_triggerEvent==='function')t_triggerEvent(document.body,'popupHidden');document.body.classList.remove('t-body_popupshowed')}else{var newPopup=[];for(var i=0;i<popupAll.length;i++){if(popupAll[i].getAttribute('data-tooltip-hook')===popupTooltipHook){popupAll[i].classList.remove('t-popup_show');newPopup.push(popupAll[i])}}
if(newPopup.length===popupAll.length){if(typeof t_triggerEvent==='function')t_triggerEvent(document.body,'popupHidden');document.body.classList.remove('t-body_popupshowed')}}
if(typeof t_triggerEvent==='function')t_triggerEvent(document.body,'popupHidden');popup.classList.remove('t-popup_show');document.body.classList.remove('t702__body_popupshowed');if(/iPhone|iPad|iPod/i.test(navigator.userAgent)&&!window.MSStream&&window.isiOSVersion&&window.isiOSVersion[0]===11){t702_unlockScroll()}
t_onFuncLoad('t_popup__addFocusOnTriggerButton',function(){t_popup__addFocusOnTriggerButton()});setTimeout(function(){var popupHide=document.querySelectorAll('.t-popup:not(.t-popup_show)');for(var i=0;i<popupHide.length;i++){popupHide[i].style.display='none'}},300);t702__triggerEvent(popup,'tildamodal:close'+popupTooltipHook)}
function t702_sendPopupEventToStatistics(popupName){var virtPage='/tilda/popup/';var virtTitle='Popup: ';if(popupName.substring(0,7)=='#popup:'){popupName=popupName.substring(7)}
virtPage+=popupName;virtTitle+=popupName;if(window.Tilda&&typeof Tilda.sendEventToStatistics=='function'){Tilda.sendEventToStatistics(virtPage,virtTitle,'',0)}else{if(ga){if(window.mainTracker!='tilda'){ga('send',{hitType:'pageview',page:virtPage,title:virtTitle})}}
if(window.mainMetrika&&window[window.mainMetrika]){window[window.mainMetrika].hit(virtPage,{title:virtTitle,referer:window.location.href})}}}
function t702_onSuccess(form){t_onFuncLoad('t_forms__onSuccess',function(){t_forms__onSuccess(form)})}
function t702__lazyLoad(){if(window.lazy==='y'||document.getElementById('allrecords').getAttribute('data-tilda-lazy')==='yes'){t_onFuncLoad('t_lazyload_update',function(){t_lazyload_update()})}}
function t702__triggerEvent(el,eventName){var event;if(typeof window.CustomEvent==='function'){event=new CustomEvent(eventName)}else if(document.createEvent){event=document.createEvent('HTMLEvents');event.initEvent(eventName,!0,!1)}else if(document.createEventObject){event=document.createEventObject();event.eventType=eventName}
event.eventName=eventName;if(el.dispatchEvent){el.dispatchEvent(event)}else if(el.fireEvent){el.fireEvent('on'+event.eventType,event)}else if(el[eventName]){el[eventName]()}else if(el['on'+eventName]){el['on'+eventName]()}}
function t367_createCookie(cookieName,cookieValue,cookieTime){var expires='';if(cookieTime){if(Number(cookieTime)>9999999){cookieTime=9999999}
var date=new Date();date.setTime(date.getTime()+cookieTime*24*60*60*1000);expires='; expires='+date.toGMTString()}
document.cookie=cookieName+'='+cookieValue+expires+'; path=/'}
function t367_readCookie(cookieName){cookieName=cookieName+'=';var allCookies=document.cookie.split(';');for(var i=0;i<allCookies.length;i++){var cookie=allCookies[i];while(cookie.charAt(0)===' '){cookie=cookie.substring(1,cookie.length)}
if(cookie.indexOf(cookieName)===0){return cookie.substring(cookieName.length,cookie.length)}}
return null}
function t367_autoInit(recid){var rec=document.querySelector('#rec'+recid);if(!rec)return;var screenMin=rec.getAttribute('data-screen-min');var screenMax=rec.getAttribute('data-screen-max');var windowWidth=window.innerWidth;if(typeof screenMin==='string'){if(windowWidth<parseInt(screenMin,10)){return!0}}
if(typeof screenMax==='string'){if(windowWidth>parseInt(screenMax,10)){return!0}}
var openerLink=rec.querySelector('.t367__opener');if(!t367_isPopupRecVisible(openerLink))return;var linkhook=openerLink.getAttribute('href');if(!linkhook)return;var cookieName=openerLink.getAttribute('data-cookie-name');var cookieTime=openerLink.getAttribute('data-cookie-time');var cookieValue='t367cookie';var cookie=t367_readCookie(cookieName);var timeout=parseInt(openerLink.getAttribute('data-trigger-time'),10)*1000;var wrapperBlock=rec.querySelector('.t367');if(!wrapperBlock)return;if(cookie)wrapperBlock.innerHTML='';else if(openerLink){setTimeout(function(){openerLink.click();wrapperBlock.innerHTML='';t367_createCookie(cookieName,cookieValue,cookieTime)},timeout)}}
function t367_isPopupRecVisible(openerLink){if(openerLink){var linkText=openerLink.getAttribute('href');var popupElement=document.querySelector('.t-popup[data-tooltip-hook="'+linkText+'"]');if(popupElement){var popupElementRec=popupElement.closest('.r');var minScreen=popupElementRec.getAttribute('data-screen-min');if(minScreen&&minScreen!==''){minScreen=minScreen.replace('px','');if(parseInt(minScreen,10)>window.innerWidth){return!1}}
var maxScreen=popupElementRec.getAttribute('data-screen-max');if(maxScreen&&maxScreen!==''){maxScreen=maxScreen.replace('px','');if(parseInt(maxScreen,10)<window.innerWidth){return!1}}}
return!0}}